@extends('layouts.sidebar')
@section('tittle', 'Download Pdf')
@section('content')
    <div class="col-lg-12">
        <div class="loading-overlay" id="loadingSpinner1" style="display: none;">
            <div class="loading-spinner"></div>
        </div>
        <div class="product-add global-shadow px-sm-30 py-sm-50 px-0 py-20 bg-white radius-xl w-100 mb-40">
            <div class="row justify-content-center">
                <div class="col-xxl-7 col-lg-10">
                    <div class="mx-sm-30 mx-20 ">

                        <div class="card add-product p-sm-30 p-20 mb-30">
                            <div class="card-body p-0">
                                <div class="card-header">
                                    <h6 class="fw-500">Recepit</h6>
                                </div>
                                <center>

                                <div class="btn-group">
                                    <a href="{{route('dashboard')}}" class="btn btn-info"  style="margin: 10px">Dashboard</a>
                                    <a href="{{route('dopdf', $bo['id'])}}" class="btn btn-info"  style="margin: 10px">Download Pdf</a>
                                </div>
                                </center>

                                <div class="add-product__body px-sm-40 px-20">

        <div class="es-wrapper-color" style="background-color:#FAFAFA"><!--[if gte mso 9]><v:background xmlns:v="urn:schemas-microsoft-com:vml" fill="t"> <v:fill type="tile" color="#fafafa"></v:fill> </v:background><![endif]--><table class="es-wrapper" width="100%" cellspacing="0" cellpadding="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;padding:0;Margin:0;width:100%;height:100%;background-repeat:repeat;background-position:center top;background-color:#FAFAFA"><tr><td valign="top" style="padding:0;Margin:0"><table class="es-header" cellspacing="0" cellpadding="0" align="center" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%;background-color:transparent;background-repeat:repeat;background-position:center top"><tr><td align="center" style="padding:0;Margin:0"><table class="es-header-body" cellspacing="0" cellpadding="0" bgcolor="#ffffff" align="center" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:600px"><tr><td align="left" style="Margin:0;padding-top:10px;padding-bottom:10px;padding-left:20px;padding-right:20px"><table width="100%" cellspacing="0" cellpadding="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td class="es-m-p0r" valign="top" align="center" style="padding:0;Margin:0;width:560px"><table width="100%" cellspacing="0" cellpadding="0" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td style="padding:0;Margin:0;padding-bottom:20px;font-size:0px" align="center"><img src="https://lgftzw.stripocdn.email/content/guids/CABINET_e49ba4194a97454a5e8b978a8512e068dff07e8d7a04ed9e171d4d054f2ae7fb/images/ama.jpeg" alt="Logo" style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic;font-size:12px" title="Logo" width="120" height="120"></td>
                                                                </tr><tr><td style="padding:0;Margin:0"><table class="es-menu" width="100%" cellspacing="0" cellpadding="0" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr class="links"><td style="Margin:0;padding-left:5px;padding-right:5px;padding-top:15px;padding-bottom:15px;border:0" width="50%" valign="top" align="center"><a target="_blank" href="" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:none;display:block;font-family:arial, 'helvetica neue', helvetica, sans-serif;color:#666666;font-size:14px">{{$bo->username}}</a></td>
                                                                                <td style="Margin:0;padding-left:5px;padding-right:5px;padding-top:15px;padding-bottom:15px;border:0" width="50%" valign="top" align="center"><a target="_blank" href="mailto:info@amazingdata.com.ng" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:none;display:block;font-family:arial, 'helvetica neue', helvetica, sans-serif;color:#666666;font-size:14px">info@amazingdata.com.ng</a></td></tr></table></td></tr></table></td></tr></table></td></tr></table></td>
                            </tr></table><table class="es-content" cellspacing="0" cellpadding="0" align="center" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%"><tr><td align="center" style="padding:0;Margin:0"><table class="es-content-body" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;border-top:10px solid #3cb0f6;width:600px;border-bottom:10px solid #3cb0f6" cellspacing="0" cellpadding="0" bgcolor="#ffffff" align="center"><tr><td align="left" style="padding:0;Margin:0;padding-left:20px;padding-right:20px;padding-top:30px"><table width="100%" cellspacing="0" cellpadding="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td valign="top" align="center" style="padding:0;Margin:0;width:560px"><table width="100%" cellspacing="0" cellpadding="0" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="left" style="padding:0;Margin:0"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;color:#666666;font-size:14px"><b>Amazingdata Mobile Transaction Record</b><br>{{\Carbon\Carbon::now()}}</p>
                                                                    </td></tr></table></td></tr></table></td></tr><tr><td align="left" style="padding:0;Margin:0;padding-top:20px;padding-left:20px;padding-right:20px"><table width="100%" cellspacing="0" cellpadding="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td valign="top" align="center" style="padding:0;Margin:0;width:560px"><table width="100%" cellspacing="0" cellpadding="0" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td class="es-m-txt-l" align="left" style="padding:0;Margin:0;padding-top:5px;padding-bottom:10px"><h3 style="Margin:0;line-height:24px;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;font-size:20px;font-style:normal;font-weight:bold;color:#3cb0f6">Dear {{\Illuminate\Support\Facades\Auth::user()->name}},</h3></td>
                                                                </tr><tr><td align="left" style="padding:0;Margin:0;padding-top:5px;padding-bottom:10px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;color:#333333;font-size:14px">These was a successful email to show that your transaction was successfully&nbsp;</p><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;color:#333333;font-size:14px"><br></p><table border="1" cellspacing="1" cellpadding="1" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:400px" class="es-table" role="presentation"><tr><td style="padding:0;Margin:0"><strong>Product:</strong></td><td style="padding:0;Margin:0"><strong>{{$bo->plan}}</strong></td>
                                                                            </tr><tr><td style="padding:0;Margin:0"><strong>Amount:</strong></td><td style="padding:0;Margin:0"><strong>₦{{number_format(intval($bo['amount'] *1))}}</strong></td></tr><tr><td style="padding:0;Margin:0"><strong>Number:</strong></td><td style="padding:0;Margin:0"><strong>{{$bo['phone']}}</strong><br></td></tr><tr><td style="padding:0;Margin:0"><strong>Refid:</strong></td><td style="padding:0;Margin:0"><strong>{{$bo['refid']}}</strong></td></tr><tr><td style="padding:0;Margin:0"><strong>Amount Before:</strong></td><td style="padding:0;Margin:0"><strong>₦{{number_format(intval($bo['fbalance'] *1))}}</strong></td></tr><tr><td style="padding:0;Margin:0"><strong>Amount After:</strong></td><td style="padding:0;Margin:0"><strong>₦{{number_format(intval($bo['balance'] *1))}}</strong><br></td></tr><tr><td style="padding:0;Margin:0"><strong>Status</strong></td><td style="padding:0;Margin:0"><strong>Delivered</strong><br></td>
                                                                            </tr></table><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;color:#333333;font-size:14px"><br><br></p></td></tr></table></td></tr></table></td></tr></table></td></tr></table></td></tr></table></div>


@endsection
